// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class gcDefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXbR4wxyxlEyXXc8p9l7xzfhU6YUFtc9U',
    appId: '1:522669596682:web:51e91d66f895d586183ff3',
    messagingSenderId: '522669596682',
    projectId: 'greekconnect-b03ba',
    authDomain: 'greekconnect-b03ba.firebaseapp.com',
    storageBucket: 'greekconnect-b03ba.firebasestorage.app',
    measurementId: 'G-JQC8LVMKR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9IDuTp7P8eVIEqk8yIa7EJwpLVhH7hic',
    appId: '1:522669596682:android:36546d740f843b10183ff3',
    messagingSenderId: '522669596682',
    projectId: 'greekconnect-b03ba',
    storageBucket: 'greekconnect-b03ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGhp8_-v4_M2wgxpZrdzLVrm0NXNAJ5N0',
    appId: '1:522669596682:ios:ca7d6ce6ffc01d30183ff3',
    messagingSenderId: '522669596682',
    projectId: 'greekconnect-b03ba',
    storageBucket: 'greekconnect-b03ba.firebasestorage.app',
    iosBundleId: 'com.example.greekConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGhp8_-v4_M2wgxpZrdzLVrm0NXNAJ5N0',
    appId: '1:522669596682:ios:ca7d6ce6ffc01d30183ff3',
    messagingSenderId: '522669596682',
    projectId: 'greekconnect-b03ba',
    storageBucket: 'greekconnect-b03ba.firebasestorage.app',
    iosBundleId: 'com.example.greekConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXbR4wxyxlEyXXc8p9l7xzfhU6YUFtc9U',
    appId: '1:522669596682:web:be44251fcc70bb4c183ff3',
    messagingSenderId: '522669596682',
    projectId: 'greekconnect-b03ba',
    authDomain: 'greekconnect-b03ba.firebaseapp.com',
    storageBucket: 'greekconnect-b03ba.firebasestorage.app',
    measurementId: 'G-LC4VTH84VF',
  );
}
